controllers:
    resource: '../src/Controller/'
    type: attribute

account:
    path: /account
    controller: App\Controller\AccountController::index

account_update:
    path: /account/update
    controller: App\Controller\AccountController::update
