# config/services.yaml

parameters:
    # Ajoutez ici les paramètres globaux pour votre application

services:
    # Configuration par défaut pour les services dans ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés aux événements, etc.

    # Rend les classes dans src/ disponibles pour être utilisées en tant que services
    # Cela crée un service par classe dont l'identifiant est le nom complet de la classe
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Définition explicite de services supplémentaires
    # Remarque : les dernières définitions remplacent toujours les précédentes

    App\EventListener\CarListener:
        arguments:
            $imageDirectory: '%kernel.project_dir%/public/images'
        tags:
            - { name: doctrine.event_listener, event: preRemove }
